function(sr_mariadb_dependency)
    set(OPT SR_MARIADB_)
    set(SR_MARIADB_WITH_UNIT_TESTS OFF)
    set(SR_MARIADB_WITH_DYNCOL OFF)
    set(SR_MARIADB_WITH_CURL OFF)
    set(SR_MARIADB_WITH_EXTERNAL_ZLIB OFF)
    set(SR_MARIADB_WITH_SSL ON)
    set(SR_MARIADB_DEFAULT_SSL_VERIFY_SERVER_CERT ON)
    foreach(plugin DIALOG PARSEC AUTH_GSSAPI_CLIENT MYSQL_OLD_PASSWORD MYSQL_CLEAR_PASSWORD REMOTE_IO REPLICATION)
        set(CLIENT_PLUGIN_${plugin} OFF)
    endforeach()
    foreach(plugin MYSQL_NATIVE_PASSWORD CACHING_SHA2_PASSWORD SHA256_PASSWORD CLIENT_ED25519)
        set(CLIENT_PLUGIN_${plugin} STATIC)
    endforeach()
    file(READ "${CMAKE_SOURCE_DIR}/dependencies.lock.json" lock)
    string(JSON url GET "${lock}" mariadb_connector_c url)
    string(JSON hash GET "${lock}" mariadb_connector_c sha256)
    FetchContent_Declare(sr_mariadb URL "${url}" URL_HASH "SHA256=${hash}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    FetchContent_MakeAvailable(sr_mariadb)
    set_target_properties(libmariadb PROPERTIES OUTPUT_NAME "libsource2root_mariadb")
    target_include_directories(libmariadb INTERFACE "${sr_mariadb_SOURCE_DIR}/include" "${sr_mariadb_BINARY_DIR}/include")
endfunction()
