option(SR_DATABASE_EXTENSION "Build the database extension" ON)
if(SR_DATABASE_EXTENSION)
    enable_language(C)
    include(FetchContent)
    file(READ "${CMAKE_SOURCE_DIR}/dependencies.lock.json" SR_DEPENDENCY_LOCK)
    string(JSON SR_SQLITE_URL GET "${SR_DEPENDENCY_LOCK}" sqlite url)
    string(JSON SR_SQLITE_HASH GET "${SR_DEPENDENCY_LOCK}" sqlite sha256)
    FetchContent_Declare(sr_sqlite URL "${SR_SQLITE_URL}" URL_HASH "SHA256=${SR_SQLITE_HASH}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
    FetchContent_MakeAvailable(sr_sqlite)
    add_library(sr_sqlite STATIC "${sr_sqlite_SOURCE_DIR}/sqlite3.c")
    target_include_directories(sr_sqlite PUBLIC "${sr_sqlite_SOURCE_DIR}")
    target_compile_definitions(sr_sqlite PRIVATE SQLITE_THREADSAFE=1 SQLITE_OMIT_LOAD_EXTENSION SQLITE_DQS=0)
    add_library(sr_database STATIC extensions/sqlite/database.cpp)
    target_include_directories(sr_database PUBLIC extensions/sqlite)
    target_compile_definitions(sr_database PUBLIC $<$<PLATFORM_ID:Linux>:_GLIBCXX_USE_CXX11_ABI=0>)
    target_link_libraries(sr_database PUBLIC sr_sqlite)
    add_library(source2root_database MODULE extensions/sqlite/extension.cpp)
    target_compile_definitions(source2root_database PRIVATE KEELS2_PLUGIN_BUILD)
    target_include_directories(source2root_database PRIVATE include)
    target_link_libraries(source2root_database PRIVATE sr_database KeelS2::SDK KeelS2::SourceSDK)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(source2root_database PRIVATE "LINKER:--exclude-libs,ALL" "LINKER:-z,defs")
    endif()
endif()
