option(SR_DHOOKS_EXTENSION "Build configured typed scripting detours" ON)
option(SR_SDKHOOKS_EXTENSION "Build typed per-entity scripting hooks" ON)
if(SR_DHOOKS_EXTENSION OR SR_SDKHOOKS_EXTENSION)
    add_library(sr_dhooks STATIC extensions/dhooks/hooks.cpp extensions/dhooks/frame.cpp extensions/dhooks/settings.cpp extensions/dhooks/call.cpp extensions/dhooks/entities.cpp)
    target_include_directories(sr_dhooks PUBLIC extensions/dhooks PRIVATE "${SR_JSON_INCLUDE}")
    target_link_libraries(sr_dhooks PUBLIC KeelS2::SDK)
endif()
if(SR_DHOOKS_EXTENSION)
    add_library(source2root_dhooks MODULE extensions/dhooks/extension.cpp)
    target_compile_definitions(source2root_dhooks PRIVATE KEELS2_PLUGIN_BUILD)
    target_include_directories(source2root_dhooks PRIVATE include)
    target_link_libraries(source2root_dhooks PRIVATE sr_dhooks KeelS2::SourceSDK)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(source2root_dhooks PRIVATE "LINKER:--exclude-libs,ALL" "LINKER:-z,defs")
    endif()
endif()

if(SR_SDKHOOKS_EXTENSION)
    add_library(sr_sdkhooks STATIC extensions/sdkhooks/hooks.cpp)
    target_include_directories(sr_sdkhooks PUBLIC extensions/sdkhooks)
    target_link_libraries(sr_sdkhooks PUBLIC sr_dhooks)
    add_library(source2root_sdkhooks MODULE extensions/sdkhooks/extension.cpp)
    target_compile_definitions(source2root_sdkhooks PRIVATE KEELS2_PLUGIN_BUILD)
    target_include_directories(source2root_sdkhooks PRIVATE include)
    target_link_libraries(source2root_sdkhooks PRIVATE sr_sdkhooks KeelS2::SourceSDK)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(source2root_sdkhooks PRIVATE "LINKER:--exclude-libs,ALL" "LINKER:-z,defs")
    endif()
endif()
