option(SR_HTTP_EXTENSION "Build asynchronous HTTP/Webternet extension" ON)
if(SR_HTTP_EXTENSION)
    enable_language(C)
    include(FetchContent)
    # Keep the selected imported target visible to the package inventory too.
    find_package(ZLIB REQUIRED)
    function(sr_curl_dependency)
        file(READ "${CMAKE_SOURCE_DIR}/dependencies.lock.json" lock)
        string(JSON url GET "${lock}" curl url)
        string(JSON hash GET "${lock}" curl sha256)
        set(BUILD_SHARED_LIBS OFF)
        set(BUILD_STATIC_LIBS ON)
        set(BUILD_TESTING OFF)
        set(BUILD_CURL_EXE OFF)
        set(BUILD_LIBCURL_DOCS OFF)
        set(BUILD_MISC_DOCS OFF)
        set(ENABLE_CURL_MANUAL OFF)
        set(CURL_DISABLE_INSTALL ON)
        set(HTTP_ONLY ON)
        set(CURL_DISABLE_ALTSVC ON)
        set(CURL_DISABLE_HSTS ON)
        set(CURL_DISABLE_COOKIES ON)
        # Keep these option handlers available so every request explicitly
        # disables ambient proxy/netrc settings through checked curl options.
        set(CURL_DISABLE_NETRC OFF)
        set(CURL_DISABLE_PROXY OFF)
        set(CURL_DISABLE_DOH ON)
        # Curl's dependency macros use set(CACHE) under an older CMP0126 policy;
        # normal variables alone are lost on the first configure.
        set(CURL_BROTLI OFF CACHE STRING "Source2Root HTTP compression selection" FORCE)
        set(CURL_ZSTD OFF CACHE STRING "Source2Root HTTP compression selection" FORCE)
        set(CURL_USE_LIBPSL OFF)
        set(CURL_USE_LIBSSH2 OFF)
        set(USE_LIBIDN2 OFF)
        set(USE_NGHTTP2 OFF)
        set(CURL_ZLIB ON CACHE STRING "Source2Root HTTP compression selection" FORCE)
        set(ENABLE_THREADED_RESOLVER ON)
        if(WIN32)
            set(CURL_USE_SCHANNEL ON)
            set(CURL_USE_OPENSSL OFF)
        else()
            set(CURL_USE_OPENSSL ON)
        endif()
        FetchContent_Declare(sr_curl URL "${url}" URL_HASH "SHA256=${hash}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
        FetchContent_MakeAvailable(sr_curl)
        set_property(DIRECTORY "${sr_curl_SOURCE_DIR}" PROPERTY EXCLUDE_FROM_ALL TRUE)
    endfunction()
    sr_curl_dependency()
    add_library(sr_http STATIC extensions/http/client.cpp)
    target_include_directories(sr_http PUBLIC extensions/http)
    target_compile_definitions(sr_http PUBLIC $<$<PLATFORM_ID:Linux>:_GLIBCXX_USE_CXX11_ABI=0>)
    target_link_libraries(sr_http PRIVATE CURL::libcurl_static)
    find_package(Threads REQUIRED)
    add_library(source2root_http MODULE extensions/http/extension.cpp)
    target_compile_definitions(source2root_http PRIVATE KEELS2_PLUGIN_BUILD)
    target_include_directories(source2root_http PRIVATE include)
    target_link_libraries(source2root_http PRIVATE sr_http Threads::Threads KeelS2::SDK KeelS2::SourceSDK)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(source2root_http PRIVATE "LINKER:--exclude-libs,ALL" "LINKER:-z,defs")
    endif()
endif()
