option(SR_GEOIP_EXTENSION "Build local GeoIP database reader extension" ON)
if(SR_GEOIP_EXTENSION)
    enable_language(C)
    include(FetchContent)
    function(sr_maxmind_dependency)
        file(READ "${CMAKE_SOURCE_DIR}/dependencies.lock.json" lock)
        string(JSON url GET "${lock}" libmaxminddb url)
        string(JSON hash GET "${lock}" libmaxminddb sha256)
        set(BUILD_SHARED_LIBS OFF)
        set(BUILD_TESTING OFF)
        set(MAXMINDDB_BUILD_BINARIES OFF)
        set(MAXMINDDB_INSTALL OFF)
        FetchContent_Declare(sr_maxmind URL "${url}" URL_HASH "SHA256=${hash}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
        FetchContent_MakeAvailable(sr_maxmind)
        set(SR_MAXMIND_SOURCE "${sr_maxmind_SOURCE_DIR}" PARENT_SCOPE)
    endfunction()
    sr_maxmind_dependency()
    add_library(sr_geoip STATIC extensions/geoip/reader.cpp)
    target_include_directories(sr_geoip PUBLIC extensions/geoip)
    target_compile_definitions(sr_geoip PUBLIC $<$<PLATFORM_ID:Linux>:_GLIBCXX_USE_CXX11_ABI=0>)
    target_link_libraries(sr_geoip PRIVATE maxminddb::maxminddb)
    find_package(Threads REQUIRED)
    add_library(source2root_geoip MODULE extensions/geoip/extension.cpp)
    target_compile_definitions(source2root_geoip PRIVATE KEELS2_PLUGIN_BUILD)
    target_include_directories(source2root_geoip PRIVATE include)
    target_link_libraries(source2root_geoip PRIVATE sr_geoip Threads::Threads KeelS2::SDK KeelS2::SourceSDK)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(source2root_geoip PRIVATE "LINKER:--exclude-libs,ALL" "LINKER:-z,defs")
    endif()
endif()
