option(SR_REGEX_EXTENSION "Build bounded PCRE2 regex extension" ON)

if(SR_REGEX_EXTENSION)
    enable_language(C)
    include(FetchContent)
    function(sr_pcre2_dependency)
        file(READ "${CMAKE_SOURCE_DIR}/dependencies.lock.json" lock)
        string(JSON url GET "${lock}" pcre2 url)
        string(JSON hash GET "${lock}" pcre2 sha256)
        set(BUILD_SHARED_LIBS OFF)
        set(BUILD_STATIC_LIBS ON)
        set(PCRE2_BUILD_PCRE2_8 ON)
        set(PCRE2_BUILD_PCRE2_16 OFF)
        set(PCRE2_BUILD_PCRE2_32 OFF)
        set(PCRE2_BUILD_PCRE2GREP OFF)
        set(PCRE2_BUILD_TESTS OFF)
        set(PCRE2_SUPPORT_JIT OFF CACHE BOOL "Source2Root uses the bounded PCRE2 interpreter" FORCE)
        set(PCRE2_SUPPORT_UNICODE ON CACHE BOOL "Source2Root supports validated UTF8" FORCE)
        set(PCRE2_STATIC_PIC ON)
        set(PCRE2_SHOW_REPORT OFF)
        FetchContent_Declare(sr_pcre2 URL "${url}" URL_HASH "SHA256=${hash}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
        FetchContent_MakeAvailable(sr_pcre2)
        set_property(DIRECTORY "${sr_pcre2_SOURCE_DIR}" PROPERTY EXCLUDE_FROM_ALL TRUE)
    endfunction()
    sr_pcre2_dependency()
    add_library(sr_regex STATIC extensions/regex/regex.cpp)
    target_include_directories(sr_regex PUBLIC extensions/regex)
    target_compile_definitions(sr_regex PUBLIC $<$<PLATFORM_ID:Linux>:_GLIBCXX_USE_CXX11_ABI=0>)
    target_link_libraries(sr_regex PRIVATE pcre2-8-static)
    add_library(source2root_regex MODULE extensions/regex/extension.cpp)
    target_compile_definitions(source2root_regex PRIVATE KEELS2_PLUGIN_BUILD)
    target_include_directories(source2root_regex PRIVATE include)
    target_link_libraries(source2root_regex PRIVATE sr_regex KeelS2::SDK KeelS2::SourceSDK)

    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(source2root_regex PRIVATE "LINKER:--exclude-libs,ALL" "LINKER:-z,defs")
    endif()
endif()
