option(SR_COUNTERSTRIKE_EXTENSION "Build CS2 player management and statistics scripting extension" ON)
if(SR_COUNTERSTRIKE_EXTENSION)
    sr_entity_backend()
    add_library(sr_cstrike STATIC extensions/cstrike/players.cpp extensions/cstrike/statistics.cpp)
    target_include_directories(sr_cstrike PUBLIC extensions/cstrike)
    target_link_libraries(sr_cstrike PUBLIC sr_sdktools KeelS2::SDK)
    add_library(source2root_cstrike MODULE extensions/cstrike/extension.cpp)
    target_compile_definitions(source2root_cstrike PRIVATE KEELS2_PLUGIN_BUILD)
    target_include_directories(source2root_cstrike PRIVATE include)
    target_link_libraries(source2root_cstrike PRIVATE sr_cstrike KeelS2::SourceSDK)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(source2root_cstrike PRIVATE "LINKER:--exclude-libs,ALL" "LINKER:-z,defs")
    endif()
endif()
