option(SR_TOPMENUS_EXTENSION "Build shared categorized plugin menus" ON)
if(SR_TOPMENUS_EXTENSION)
    add_library(sr_topmenus STATIC extensions/topmenus/catalog.cpp)
    target_include_directories(sr_topmenus PUBLIC extensions/topmenus)
    target_compile_definitions(sr_topmenus PUBLIC $<$<PLATFORM_ID:Linux>:_GLIBCXX_USE_CXX11_ABI=0>)
    add_library(source2root_topmenus MODULE extensions/topmenus/extension.cpp)
    target_compile_definitions(source2root_topmenus PRIVATE KEELS2_PLUGIN_BUILD)
    target_include_directories(source2root_topmenus PRIVATE include)
    target_link_libraries(source2root_topmenus PRIVATE sr_topmenus KeelS2::SDK KeelS2::SourceSDK)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(source2root_topmenus PRIVATE "LINKER:--exclude-libs,ALL" "LINKER:-z,defs")
    endif()
endif()
