option(SR_SDKTOOLS_EXTENSION "Build entity/schema scripting extension" ON)
function(sr_entity_backend)
    if(NOT TARGET sr_sdktools)
        add_library(sr_sdktools STATIC extensions/sdktools/entities.cpp)
        target_include_directories(sr_sdktools PUBLIC extensions/sdktools)
        target_link_libraries(sr_sdktools PUBLIC KeelS2::SDK)
    endif()
endfunction()

if(SR_SDKTOOLS_EXTENSION)
    sr_entity_backend()
    add_library(source2root_sdktools MODULE extensions/sdktools/extension.cpp)
    target_compile_definitions(source2root_sdktools PRIVATE KEELS2_PLUGIN_BUILD)
    target_include_directories(source2root_sdktools PRIVATE include)
    target_link_libraries(source2root_sdktools PRIVATE sr_sdktools KeelS2::SourceSDK)

    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        target_link_options(source2root_sdktools PRIVATE "LINKER:--exclude-libs,ALL" "LINKER:-z,defs")
    endif()
endif()
